# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TorusDirectSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TorusDirectSDKDemo

  pod 'OAuthSwift', '~> 2.0.0'

  target 'TorusDirectSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TorusDirectSDKDemoUITests' do
    # Pods for testing
  end

end
