# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'cptest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # pod 'Torus-utils', '~>'
  pod 'CustomAuth', :path=>"../"
  
  pod 'tkey-rust-ios', :path=>"../../libtkey-pkg"
  
 

  
  # Pods for cptest
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
  	
