# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cptest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'secp256k1.c', '~> 0.1.2'
  pod 'Torus-utils', '~> 0.1.1'
  pod 'Torus-directSDK', :path=>"../"
  # Pods for cptest
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
  	
